### ISSUE TITLE
Change references to bitbucket to point to the github repo

### ISSUE THREAD

**Issue by kvdblom** [ADA-research/Sparkle#11]
Some old references still point to the bitbucket repository, it would be good to correct them so they point to this new github repository.

Specifically, I saw the following that link to bitbucket:
- https://ada.liacs.nl/projects/sparkle/
- https://sparkle-ai.readthedocs.io/en/main/userguide/userguide.html#get-a-copy-of-sparkle

Maybe there are others.

**Comment by thijssnelleman** [comment]
- Read the docs will be fixed with new deploy this week
- New ADA website is under development
