### ISSUE TITLE
Support feature groups for algorithm selection

### ISSUE THREAD

**Issue by hadarshavit** [ADA-research/Sparkle#20]
Features describing instances are usually split into feature groups. It is then possible to decide which feature groups to extract and save time by extracting only the necessary feature groups.
AutoFolio supports feature groups, however only with ASlib scenario as an input.
Currently, Sparkle constructs the portfolio selector with CSV files.
To improve the performance we need to:

- Allow the feature extractor to specify feature groups
- Extract the features based on separate feature groups, and measure the extraction time accordingly
- Pass the feature groups to the selector constructor

**Comment by thijssnelleman** [comment]
Extracted features are now specified by groups. Only the last step is to be done, but preferably after the decoupling of AutoFolio.

**Comment by thijssnelleman** [comment]
Issue was completed weeks ago
